### ISSUE TITLE
Feed no longer updating

### ISSUE THREAD

**Issue by kaustral** [renolc/sinfest-rss#2]
Last update Mon Jun 24 2019 02:00:00

I use Feedbro on Firefox. Unsure if it works anywhere else.

**Comment by renolc** [comment]
You're right. I had recently switched main development machines and forgot about this cron job. I have restarted it on my new setup, so it should start updating again normally. Apologies for the lapse. 😅

**Comment by kaustral** [comment]
Wow, already fixed :D
Thanks a lot
